/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Signup.main;

import java.awt.Color;
import java.awt.Font;
import org.jdesktop.animation.timing.Animator;
import org.jdesktop.animation.timing.TimingTarget;
import org.jdesktop.animation.timing.TimingTargetAdapter;

import java.sql.Connection;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;
import java.sql.ResultSet; 
import Login.GetID;  
import University.Jconnection;

/**
 *
 * @author SAJID
 */
public class Main3 extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    
    Connection conn=null;
    PreparedStatement ps=null;
    ResultSet rs = null;
    
    
    private Animator animatorLogin;
    private Animator animatorBody;
    private Boolean signIn=false;

    
    public Main3() {
        initComponents();
        conn=Jconnection.CC();
        GetID.press=0;
        getContentPane().setBackground(new Color(245,245,245));
        
        winButton1.initEvent(this);
        TimingTarget targetLogin = new TimingTargetAdapter() {
            @Override
            public void timingEvent(float fraction) {
                if (GetID.press==2) {
                    background1.setAnimate(1f - fraction);
                } else if(GetID.press==1){
                    background1.setAnimate(fraction);
                }
            }

            @Override
            public void end() {
                if(GetID.press==1)
                {
                    System.out.println(GetID.press);
                    panelLogin.setVisible(false);
                    background1.setShowPaint(true);
                    Login.main.Main mp=new Login.main.Main();
                    mp.show();
                    dispose();
                }
                else if(GetID.press==2)
                {
                    
                    panelLogin.setVisible(false);
                    background1.setShowPaint(true);
                    Main2 u = new Main2(); 
                    u.show();
                    dispose();
                }
            }
        };
        animatorLogin = new Animator(1500, targetLogin);
        animatorLogin.setResolution(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background1 = new Login.swing.Background();
        panelLogin = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        kButton2 = new com.k33ptoo.components.KButton();
        kButton3 = new com.k33ptoo.components.KButton();
        jSeparator2 = new javax.swing.JSeparator();
        kButton1 = new com.k33ptoo.components.KButton();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        kButton4 = new com.k33ptoo.components.KButton();
        jCheckBox1 = new javax.swing.JCheckBox();
        textField1 = new Signup.swing.TextField();
        passwordField1 = new Signup.swing.PasswordField();
        passwordField2 = new Signup.swing.PasswordField();
        winButton1 = new Signup.win_button3.WinButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1300, 800));
        setUndecorated(true);

        background1.setLayout(new java.awt.CardLayout());

        panelLogin.setBackground(new java.awt.Color(30, 30, 30));
        panelLogin.setPreferredSize(new java.awt.Dimension(1300, 800));
        panelLogin.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        panelLogin.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1240, 10, 18, 18));

        jPanel2.setBackground(new java.awt.Color(30, 30, 30));

        kButton2.setText("3");
        kButton2.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        kButton2.setkBorderRadius(50);
        kButton2.setkEndColor(new java.awt.Color(0, 153, 153));
        kButton2.setkHoverColor(new java.awt.Color(0, 153, 153));
        kButton2.setkHoverEndColor(new java.awt.Color(0, 153, 153));
        kButton2.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        kButton2.setkHoverStartColor(new java.awt.Color(0, 153, 153));
        kButton2.setkIndicatorColor(new java.awt.Color(0, 153, 153));
        kButton2.setkPressedColor(new java.awt.Color(0, 153, 153));
        kButton2.setkSelectedColor(new java.awt.Color(0, 153, 153));
        kButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kButton2ActionPerformed(evt);
            }
        });

        kButton3.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        kButton3.setkBackGroundColor(new java.awt.Color(255, 255, 255));
        kButton3.setkBorderRadius(50);
        kButton3.setkEndColor(new java.awt.Color(255, 255, 255));
        kButton3.setkForeGround(new java.awt.Color(0, 0, 0));
        kButton3.setkHoverEndColor(new java.awt.Color(255, 255, 255));
        kButton3.setkHoverForeGround(new java.awt.Color(0, 0, 0));
        kButton3.setkHoverStartColor(new java.awt.Color(255, 255, 255));
        kButton3.setkPressedColor(new java.awt.Color(255, 255, 255));
        kButton3.setkSelectedColor(new java.awt.Color(255, 255, 255));
        kButton3.setkStartColor(new java.awt.Color(255, 255, 255));
        kButton3.setLabel("1");
        kButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kButton3ActionPerformed(evt);
            }
        });

        jSeparator2.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(204, 204, 204)));

        kButton1.setBorder(null);
        kButton1.setText("2");
        kButton1.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        kButton1.setkBackGroundColor(new java.awt.Color(255, 255, 255));
        kButton1.setkBorderRadius(50);
        kButton1.setkEndColor(new java.awt.Color(255, 255, 255));
        kButton1.setkForeGround(new java.awt.Color(0, 0, 0));
        kButton1.setkHoverEndColor(new java.awt.Color(255, 255, 255));
        kButton1.setkHoverForeGround(new java.awt.Color(0, 0, 0));
        kButton1.setkHoverStartColor(new java.awt.Color(255, 255, 255));
        kButton1.setkPressedColor(new java.awt.Color(255, 255, 255));
        kButton1.setkSelectedColor(new java.awt.Color(255, 255, 255));
        kButton1.setkStartColor(new java.awt.Color(255, 255, 255));
        kButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kButton1ActionPerformed(evt);
            }
        });

        jSeparator4.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(204, 204, 204)));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 530, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(kButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGap(40, 40, 40)
                            .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGap(30, 30, 30)
                            .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(kButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(kButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(kButton3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(kButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(kButton2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGap(20, 20, 20)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        panelLogin.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 550, 530, 100));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Signup/icon/pngwing.com.png"))); // NOI18N
        panelLogin.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 180, 400, 400));

        jPanel1.setBackground(new java.awt.Color(30, 30, 30));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(30, 30, 30));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Signup/icon/icons8-sign-up-58.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        jLabel1.setOpaque(true);
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(316, 26, 50, -1));

        kButton4.setText("Submit");
        kButton4.setFont(new java.awt.Font("Century Gothic", 1, 20)); // NOI18N
        kButton4.setkBackGroundColor(new java.awt.Color(51, 102, 255));
        kButton4.setkBorderRadius(40);
        kButton4.setkEndColor(new java.awt.Color(102, 255, 255));
        kButton4.setkForeGround(new java.awt.Color(0, 0, 102));
        kButton4.setkHoverEndColor(new java.awt.Color(0, 0, 102));
        kButton4.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        kButton4.setkHoverStartColor(new java.awt.Color(0, 51, 102));
        kButton4.setkSelectedColor(new java.awt.Color(102, 255, 255));
        kButton4.setkStartColor(new java.awt.Color(153, 255, 204));
        kButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(kButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 350, 140, -1));

        jCheckBox1.setForeground(new java.awt.Color(204, 204, 204));
        jCheckBox1.setText(" I agree to the Terms of Service and Privacy Policy");
        jPanel1.add(jCheckBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 330, -1, -1));

        textField1.setBackground(new java.awt.Color(30, 30, 30));
        textField1.setForeground(new java.awt.Color(255, 255, 255));
        textField1.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        textField1.setLabelText("User Name");
        jPanel1.add(textField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 110, 380, -1));

        passwordField1.setBackground(new java.awt.Color(30, 30, 30));
        passwordField1.setForeground(new java.awt.Color(255, 255, 255));
        passwordField1.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        passwordField1.setLabelText("Confirm Password");
        jPanel1.add(passwordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 250, 380, -1));

        passwordField2.setBackground(new java.awt.Color(30, 30, 30));
        passwordField2.setForeground(new java.awt.Color(255, 255, 255));
        passwordField2.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        passwordField2.setLabelText("Password");
        jPanel1.add(passwordField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 180, 380, -1));

        panelLogin.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, 690, 440));
        panelLogin.add(winButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1240, 10, -1, -1));

        background1.add(panelLogin, "card2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void kButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kButton2ActionPerformed

    private void kButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kButton3ActionPerformed

    private void kButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kButton1ActionPerformed

    private void kButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kButton4ActionPerformed
        // TODO add your handling code here:
        try{
            
            
            String usr = textField1.getText(), pass = passwordField1.getText(), cpass =  passwordField2.getText(); 
            System.out.println("kire");
            
            if(pass.equals(cpass) && pass.length()!=0 && usr.length()!=0 )
            {
                JOptionPane.showMessageDialog(null, "Successful");
                
            String query="Update student_information set Username = '"+usr+"' , Password = '"+pass+"'  where ID = " + GetID.ID;
            ps=conn.prepareStatement(query);
            //rs = ps.excuteQuery();
            
            //System.out.println(year);
            ps.executeUpdate();
            GetID.press=1;
            jPanel1.setVisible(false);
            jPanel2.setVisible(false);
            jLabel3.setVisible(false);
            animatorLogin.start();                
            }
            else
            {
                JOptionPane.showMessageDialog(null, "Fill the form properly");
            }
            
            
        }catch(Exception exp){
            JOptionPane.showMessageDialog(null, exp);
            
            
        }
        
        

        

    }//GEN-LAST:event_kButton4ActionPerformed

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:
        
        GetID.press=2;
        jPanel1.setVisible(false);
        jPanel2.setVisible(false);
        jLabel3.setVisible(false);
        animatorLogin.start();
        
    }//GEN-LAST:event_jLabel2MouseClicked
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main3().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Login.swing.Background background1;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator4;
    private com.k33ptoo.components.KButton kButton1;
    private com.k33ptoo.components.KButton kButton2;
    private com.k33ptoo.components.KButton kButton3;
    private com.k33ptoo.components.KButton kButton4;
    private javax.swing.JPanel panelLogin;
    private Signup.swing.PasswordField passwordField1;
    private Signup.swing.PasswordField passwordField2;
    private Signup.swing.TextField textField1;
    private Signup.win_button3.WinButton winButton1;
    // End of variables declaration//GEN-END:variables
}
