/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Signup_Login.main;

import Login.GetID;
import java.awt.Color;
import org.jdesktop.animation.timing.Animator;
import org.jdesktop.animation.timing.TimingTarget;
import org.jdesktop.animation.timing.TimingTargetAdapter;

/**
 *
 * @author SAJID
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    private Animator animatorLogin;
    private int signIn;

    
    public Main() {
        initComponents();
        GetID.press=0;
        getContentPane().setBackground(new Color(245,245,245));
        winButton2.initEvent(this);
        TimingTarget targetLogin = new TimingTargetAdapter() {
            @Override
            public void timingEvent(float fraction) {
                if (GetID.press==2) {
                    background1.setAnimate(1f - fraction);
                } else if(GetID.press==1){
                    background1.setAnimate(fraction);
                }
            }

            @Override
            public void end() {
                if (GetID.press==1) {
                    panelLogin.setVisible(false);
                    background1.setShowPaint(true);
                    if(signIn==1){
                        Signup.main.Main1 mp=new Signup.main.Main1();
                        mp.setVisible(true);
                        dispose();
                    }
                    else {
                        Login.main.Main mp=new Login.main.Main();
                        mp.setVisible(true);
                        dispose();
                    }
                    
                } 
                else if(GetID.press==2)
                {
                    panelLogin.setVisible(false);
                    background1.setShowPaint(true);
                    main.Test u=new main.Test();
                    u.show();
                    dispose();
                }
            }
        };
        
        animatorLogin = new Animator(1500, targetLogin);
        animatorLogin.setResolution(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background1 = new Login.swing.Background();
        panelLogin = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        winButton2 = new Signup_Login.win_button1.WinButton();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        kButton2 = new com.k33ptoo.components.KButton();
        kButton3 = new com.k33ptoo.components.KButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1300, 800));
        setUndecorated(true);

        background1.setOpaque(true);
        background1.setLayout(new java.awt.CardLayout());

        panelLogin.setBackground(new java.awt.Color(30, 30, 30));
        panelLogin.setPreferredSize(new java.awt.Dimension(1300, 800));
        panelLogin.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        panelLogin.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1240, 10, 18, 18));
        panelLogin.add(winButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1240, 10, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Signup_Login/icon/Lovepik_com-401473585-studying.png"))); // NOI18N
        panelLogin.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(94, 114, 550, -1));

        jPanel1.setBackground(new java.awt.Color(30, 30, 30));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 204));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Setup a profile to get started");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 90, 360, -1));

        kButton2.setText("Sign up");
        kButton2.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        kButton2.setkBorderRadius(45);
        kButton2.setkEndColor(new java.awt.Color(157, 153, 255));
        kButton2.setkHoverEndColor(new java.awt.Color(153, 255, 204));
        kButton2.setkHoverForeGround(new java.awt.Color(0, 0, 102));
        kButton2.setkHoverStartColor(new java.awt.Color(153, 255, 255));
        kButton2.setkPressedColor(new java.awt.Color(153, 153, 153));
        kButton2.setkSelectedColor(new java.awt.Color(153, 255, 255));
        kButton2.setkStartColor(new java.awt.Color(0, 0, 102));
        kButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(kButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 290, 270, -1));

        kButton3.setText("Log in");
        kButton3.setToolTipText("");
        kButton3.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        kButton3.setkBorderRadius(45);
        kButton3.setkEndColor(new java.awt.Color(157, 153, 255));
        kButton3.setkHoverEndColor(new java.awt.Color(153, 255, 204));
        kButton3.setkHoverForeGround(new java.awt.Color(0, 0, 102));
        kButton3.setkHoverStartColor(new java.awt.Color(153, 255, 255));
        kButton3.setkPressedColor(new java.awt.Color(153, 153, 153));
        kButton3.setkSelectedColor(new java.awt.Color(153, 255, 255));
        kButton3.setkStartColor(new java.awt.Color(0, 0, 102));
        kButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(kButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 200, 270, -1));

        panelLogin.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(703, 134, 500, 430));

        background1.add(panelLogin, "card2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void kButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kButton2ActionPerformed
        // TODO add your handling code here:
        signIn=1;
        GetID.press=1;
        jPanel1.setVisible(false);
        jLabel2.setVisible(false);
        animatorLogin.start();
    }//GEN-LAST:event_kButton2ActionPerformed

    private void kButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kButton3ActionPerformed
        // TODO add your handling code here:
        signIn=2;
        GetID.press=1;
        jPanel1.setVisible(false);
        jLabel2.setVisible(false);
        animatorLogin.start();
    }//GEN-LAST:event_kButton3ActionPerformed

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:
        
        GetID.press=2;
        jPanel1.setVisible(false);
        jLabel2.setVisible(false);
        animatorLogin.start();
    }//GEN-LAST:event_jLabel3MouseClicked

   
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Login.swing.Background background1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private com.k33ptoo.components.KButton kButton2;
    private com.k33ptoo.components.KButton kButton3;
    private javax.swing.JPanel panelLogin;
    private Signup_Login.win_button1.WinButton winButton2;
    // End of variables declaration//GEN-END:variables
}
