/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package University;

import Login.GetID;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.ImageIcon;
import javax.swing.JFrame;

/**
 *
 * @author SAJID
 */
public class default_uni extends javax.swing.JPanel {

    /**
     * Creates new form default_uni
     */
    JFrame fra;
    Color color;
    public default_uni() {
        initComponents();
    }

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pro = new progressbar.ProgressBarCustom();
        pics = new javax.swing.JLabel();
        qsrank = new javax.swing.JLabel();
        Uniname = new javax.swing.JLabel();
        country = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 0, 0));
        setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        setPreferredSize(new java.awt.Dimension(350, 350));
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pro.setBackground(new java.awt.Color(204, 0, 51));
        pro.setString("");
        add(pro, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 340, 350, 10));

        pics.setForeground(new java.awt.Color(255, 0, 0));
        pics.setOpaque(true);
        pics.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                picsMouseClicked(evt);
            }
        });
        add(pics, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 350, 220));

        qsrank.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        qsrank.setForeground(new java.awt.Color(255, 255, 255));
        qsrank.setText("jLabel1");
        qsrank.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                qsrankMouseClicked(evt);
            }
        });
        add(qsrank, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 300, 350, 40));

        Uniname.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        Uniname.setForeground(new java.awt.Color(255, 255, 255));
        Uniname.setText("jLabel1");
        Uniname.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                UninameMouseClicked(evt);
            }
        });
        add(Uniname, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, 350, 40));

        country.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        country.setForeground(new java.awt.Color(255, 255, 255));
        country.setText("jLabel1");
        country.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                countryMouseClicked(evt);
            }
        });
        add(country, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 350, 40));
    }// </editor-fold>//GEN-END:initComponents

    public void getObj(JFrame fram) {
        fra=fram;
    }
    
    
    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        // TODO add your handling code here:
        System.out.println(qsrank.getText());
        String str = qsrank.getText(); 
        str = str.substring(10, str.length());
        
        System.out.println(str);
        System.out.println(str.length());
        GetID.press=1;
        University.uni_profile u = new University.uni_profile(str,pro.getBackground()); 
        u.show();
        fra.dispose();        
    }//GEN-LAST:event_formMouseClicked

    private void picsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_picsMouseClicked
        // TODO add your handling code here:
        System.out.println(qsrank.getText());
        String str = qsrank.getText(); 
        str = str.substring(10, str.length());
        
        System.out.println(str);
        System.out.println(str.length());
        GetID.press=1;
        University.uni_profile u = new University.uni_profile(str,pro.getBackground()); 
        u.show();
        fra.dispose();
    }//GEN-LAST:event_picsMouseClicked

    private void UninameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UninameMouseClicked
        // TODO add your handling code here:
        System.out.println(qsrank.getText());
        String str = qsrank.getText(); 
        str = str.substring(10, str.length());
        GetID.press=1;
        
        System.out.println(str);
        System.out.println(str.length());
        University.uni_profile u = new University.uni_profile(str,pro.getBackground()); 
        u.show();
        fra.dispose();
    }//GEN-LAST:event_UninameMouseClicked

    private void countryMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_countryMouseClicked
        // TODO add your handling code here:
        System.out.println(qsrank.getText());
        String str = qsrank.getText(); 
        str = str.substring(10, str.length());
        GetID.press=1;        
        System.out.println(str);
        System.out.println(str.length());
        University.uni_profile u = new University.uni_profile(str,pro.getBackground()); 
        u.show();
        fra.dispose();

    }//GEN-LAST:event_countryMouseClicked

    private void qsrankMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_qsrankMouseClicked
        // TODO add your handling code here:
        System.out.println(qsrank.getText());
        String str = qsrank.getText(); 
        str = str.substring(10, str.length());
        GetID.press=1;
        
        System.out.println(str);
        System.out.println(str.length());
        University.uni_profile u = new University.uni_profile(str,pro.getBackground()); 
        u.show();
        fra.dispose();

    }//GEN-LAST:event_qsrankMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel Uniname;
    public javax.swing.JLabel country;
    public javax.swing.JLabel pics;
    public progressbar.ProgressBarCustom pro;
    public javax.swing.JLabel qsrank;
    // End of variables declaration//GEN-END:variables
}
