/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Login.main;

import University.Jconnection;
import java.awt.Color;
import java.awt.Font;
import org.jdesktop.animation.timing.Animator;
import org.jdesktop.animation.timing.TimingTarget;
import org.jdesktop.animation.timing.TimingTargetAdapter;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.DriverManager;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import Login.GetID; 

/**
 *
 * @author SAJID
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    
    Connection conn=null;
    PreparedStatement ps=null;
    ResultSet rs=null;
    
    private Animator animatorLogin;
    private Boolean signIn;
    private int k=0;

    
    public Main() {
        initComponents();
        conn=Jconnection.CC();
        GetID.press=0;
        k=0;
        getContentPane().setBackground(new Color(245,245,245));
        winButton1.initEvent(this);

        TimingTarget targetLogin = new TimingTargetAdapter() {
            @Override
            public void timingEvent(float fraction) {
                if (GetID.press==2) {
                    background1.setAnimate(1f - fraction);
                } else if(GetID.press==1){
                    background1.setAnimate(fraction);
                }
            }
            
            @Override
            public void end() {
                if(GetID.press==1)
                {
                    panelLogin.setVisible(false);
                    background1.setShowPaint(true);
                    com.raven.main.Main obj=new  com.raven.main.Main();
                    obj.show();
                    dispose();
                }
                else if(GetID.press==2)
                {
                    panelLogin.setVisible(false);
                    background1.setShowPaint(true);
                    if(k==0)
                    {   
                        Signup_Login.main.Main u = new Signup_Login.main.Main(); 
                        u.show();
                        dispose();
                    }
                    else if(k==1)
                    {
                        Signup.main.Main1 u=new Signup.main.Main1();
                        u.show();
                        dispose();
                    }
                }
                else
                {
                    enableLogin(true);
                    txtUser.grabFocus();
                }
            }
        };
        
        animatorLogin = new Animator(1500, targetLogin);
        animatorLogin.setResolution(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background1 = new Login.swing.Background();
        panelLogin = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        winButton1 = new Login.win_button1.WinButton();
        jPanel1 = new javax.swing.JPanel();
        cmdSignIn = new com.k33ptoo.components.KButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtUser = new Login.swing.TextField();
        txtPass = new Login.swing.PasswordField();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1300, 800));
        setUndecorated(true);

        background1.setBackground(new java.awt.Color(30, 30, 30));
        background1.setOpaque(true);
        background1.setLayout(new java.awt.CardLayout());

        panelLogin.setBackground(new java.awt.Color(30, 30, 30));
        panelLogin.setPreferredSize(new java.awt.Dimension(1300, 800));
        panelLogin.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        panelLogin.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1240, 10, 18, 18));
        panelLogin.add(winButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1240, 10, -1, -1));

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setOpaque(false);

        cmdSignIn.setText("Login");
        cmdSignIn.setFont(new java.awt.Font("Century Gothic", 1, 20)); // NOI18N
        cmdSignIn.setkBackGroundColor(new java.awt.Color(51, 102, 255));
        cmdSignIn.setkBorderRadius(40);
        cmdSignIn.setkEndColor(new java.awt.Color(102, 255, 255));
        cmdSignIn.setkForeGround(new java.awt.Color(0, 0, 102));
        cmdSignIn.setkHoverEndColor(new java.awt.Color(0, 0, 102));
        cmdSignIn.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        cmdSignIn.setkHoverStartColor(new java.awt.Color(0, 51, 102));
        cmdSignIn.setkSelectedColor(new java.awt.Color(102, 255, 255));
        cmdSignIn.setkStartColor(new java.awt.Color(153, 255, 204));
        cmdSignIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdSignInActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 204, 204));
        jLabel5.setText("Or");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 204, 204));
        jLabel4.setText("Create a new account");
        jLabel4.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(204, 204, 204)));
        jLabel4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel4MousePressed(evt);
            }
        });

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Login/icon/icons8-male-user-70.png"))); // NOI18N

        txtUser.setBackground(new java.awt.Color(30, 30, 30));
        txtUser.setForeground(new java.awt.Color(255, 255, 255));
        txtUser.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        txtUser.setLabelText("User Name");
        txtUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUserActionPerformed(evt);
            }
        });

        txtPass.setBackground(new java.awt.Color(30, 30, 30));
        txtPass.setForeground(new java.awt.Color(255, 255, 255));
        txtPass.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        txtPass.setLabelText("Password");
        txtPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPassActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(txtUser, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(txtPass, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addComponent(cmdSignIn, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(210, 210, 210)
                .addComponent(jLabel5))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(150, 150, 150)
                .addComponent(jLabel4))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addComponent(jLabel1)
                .addGap(10, 10, 10)
                .addComponent(txtUser, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(txtPass, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(cmdSignIn, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        panelLogin.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(143, 80, -1, 550));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Login/icon/Lovepik_com-610738087-Vector illustration complete celebration shield.png"))); // NOI18N
        panelLogin.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(665, 80, -1, -1));

        background1.add(panelLogin, "card2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cmdSignInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdSignInActionPerformed
        // TODO add your handling code here:
        
        if (!animatorLogin.isRunning()) {
            String user = txtUser.getText().trim();
            String pass = String.valueOf(txtPass.getPassword());
            boolean action = true;
            signIn=true;
            if (user.equals("")) {
                txtUser.setHelperText("Please input user name");
                txtUser.grabFocus();
                action = false;
            }
            if (pass.equals("")) {
                txtPass.setHelperText("Please input password");
                if (action) {
                    txtPass.grabFocus();
                }
                action = false;
            }
            if (action) {

                
                String sql="select ID from student_information where Username=? and Password=?";
                int id=-1;
                try{
                    ps = conn.prepareStatement(sql);
                    ps.setString(1, txtUser.getText());
                    ps.setString(2, txtPass.getText());

                    rs = ps.executeQuery();
                    if(rs.next()){
                        JOptionPane.showMessageDialog(null, "Username and Password is Correct");
                        id=rs.getInt(1);
                        GetID.flag=1;
                        GetID.ID=id;
                        GetID.press=1;
                        jPanel1.setVisible(false);
                        jLabel2.setVisible(false);
                        animatorLogin.start();
                        enableLogin(false);
                        
                    }
                    else{
                        GetID.ID=-1;
                        GetID.flag=0;
                        JOptionPane.showMessageDialog(null, "Username and Password is not Correct");
                    }
                }catch(Exception e){
                    JOptionPane.showMessageDialog(null, e);
                }
            }
        }
        
        
    }//GEN-LAST:event_cmdSignInActionPerformed

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        // TODO add your handling code here:
        
        GetID.press=2;
        k=1;
        jPanel1.setVisible(false);
        jLabel2.setVisible(false);
        animatorLogin.start();
        enableLogin(false);
        
    }//GEN-LAST:event_jLabel4MouseClicked

    private void jLabel4MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel4MousePressed

    private void txtUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUserActionPerformed

    private void txtPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPassActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtPassActionPerformed

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:
        
        GetID.press=2;
        jPanel1.setVisible(false);
        jLabel2.setVisible(false);
        animatorLogin.start();
        enableLogin(false);
    }//GEN-LAST:event_jLabel3MouseClicked

    private void enableLogin(boolean action) {
        txtUser.setEditable(action);
        txtPass.setEditable(action);
        cmdSignIn.setEnabled(action);
    }

    public void clearLogin() {
        txtUser.setText("");
        txtPass.setText("");
        txtUser.setHelperText("");
        txtPass.setHelperText("");
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Login.swing.Background background1;
    private com.k33ptoo.components.KButton cmdSignIn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel panelLogin;
    private Login.swing.PasswordField txtPass;
    private Login.swing.TextField txtUser;
    private Login.win_button1.WinButton winButton1;
    // End of variables declaration//GEN-END:variables
}
